/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 362 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
#line 3 "example11.c"
__inline int bitcount(int input ) ;
#line 5 "example11.c"
__inline int bitcount(int input ) 
{ 
  int output ;
  int i ;
  unsigned long __cil_tmp4 ;
  unsigned long __cil_tmp5 ;
  int __cil_tmp6 ;

  {
#line 6
  output = 0;
#line 7
  i = 0;
#line 7
  while (1) {
    {
#line 7
    __cil_tmp4 = 8UL * 4UL;
#line 7
    __cil_tmp5 = (unsigned long )i;
#line 7
    if (! (__cil_tmp5 < __cil_tmp4)) {
#line 7
      break;
    }
    }
    {
#line 8
    __cil_tmp6 = 1 << i;
#line 8
    if (input & __cil_tmp6) {
#line 8
      output ++;
    }
    }
#line 7
    i ++;
  }
#line 10
  return (output);
}
}
#line 13 "example11.c"
int main(int argc , int **argv ) 
{ 
  int tmp ;
  char const   * __restrict  __cil_tmp4 ;

  {
#line 14
  tmp = bitcount(11);
#line 14
  __cil_tmp4 = (char const   * __restrict  )"%d\n";
#line 14
  printf(__cil_tmp4, tmp);
#line 15
  return (0);
}
}
